baseURL = 'https://pastekitlab.github.io/'
languageCode = 'zh-cn'
title = '我的博客'

enableRobotsTXT = true
paginate = 6

[params]
  description = '一个 Hugo 高级博客'
  author = '你的名字'

[sitemap]
  changefreq = 'weekly'
  priority = 0.5

[taxonomies]
  tag = 'tags'
  category = 'categories'

[outputs]
  home = ['HTML', 'JSON']

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 20
